### ISSUE TITLE
InvalidUrlException

### ISSUE THREAD

**Issue by lordcirth** [smallhadroncollider/brok#1]
I tried running brok on the SaltStack html docs:

```
root@salt-dev:~/brok# brok --cache 604800 /root/salt/doc/_build/html/ref/modules/all/* > /dev/null
brok: InvalidUrlException "http://user:password&#64;securesite.com/secret-file.json&quot;" "Invalid URL"
root@salt-dev:~/brok#
```

While this certainly is an invalid URL, I think this should be reported as an error, not cause a crash.

**Comment by smallhadroncollider** [comment]
Agreed!

The URL parser I wrote must be picking up some invalid URLs (it's still early days) and passing them along to http, which has a more detailed parser.

**Comment by smallhadroncollider** [comment]
Ah, I'd put my Exception capturing too low down in the code!

**Comment by smallhadroncollider** [comment]
Fixed in the `develop` branch. I'll do a fresh release in the morning.

**Comment by smallhadroncollider** [comment]
I lied. Have a release now: https://github.com/smallhadroncollider/brok/releases/tag/0.1.1
