### ISSUE TITLE
 release has only a binary for macOS?

### ISSUE THREAD

**Issue by juliangaal** [smallhadroncollider/brok#11]
Latest release (1.0.0) has only a binary for macOS. the `.deb` file seems to missing as well. Thanks!

**Comment by smallhadroncollider** [comment]
Sorry, they’ve not released the Docker box for Stackage 15.8. I’ll upload a build once that’s up.

**Comment by smallhadroncollider** [comment]
I've built it with 15.7 and uploaded now.

**Comment by juliangaal** [comment]
great, thanks

EDIT: works beautifully, what a nice little tool!
