### ISSUE TITLE
Don't check duplicated URLs

### ISSUE THREAD

**Issue by kairichard** [smallhadroncollider/brok#14]
First off thanks for making this tool, I am currently using it to validate the links in my static website. However, since there are links in the footer and header which are on all the generated pages `brok` finds more than 600 links to validate from 90% are duplicates. 

#### Why is this a problem? 
First, it makes the CI pipeline slower, and second, it generates unneeded traffic for certain resources. 

I would have tried to do merge request myself but since I am not familiar with Haskell I did not want start that endeavor - although the syntax looks quite concise and compact. 

So maybe adding an option to deduplicate the found links would be awesome.

**Comment by smallhadroncollider** [comment]
I'll be honest, I thought it already did! Will add that to the list.

**Comment by smallhadroncollider** [comment]
Fixed in the next release.
