### ISSUE TITLE
Document how to use it in a simple docker container

### ISSUE THREAD

**Issue by boillodmanuel** [smallhadroncollider/brok#16]
As it's not as easy to install it (see #15), this will be great to have Dockerfile or at least some steps to make it working on docker

**Comment by boillodmanuel** [comment]
I make it working with

```bash
docker run --rm -it -v=$PWD:/wiki -w=/wiki debian:buster-slim /bin/bash
```

Then inside container:

```bash
apt-get update
apt-get install -y wget
rm -rf /var/lib/apt/lists/*
VERSION=1.0.0
wget -q -O "brok-${VERSION}.deb" "https://github.com/smallhadroncollider/brok/releases/download/${VERSION}/brok-${VERSION}_x86-64-linux.deb"
dpkg -i "brok-${VERSION}.deb"
brok
```

**Comment by smallhadroncollider** [comment]
Sorry, I'm not much of a Docker user, so probably best if someone else does this.

**Comment by smallhadroncollider** [comment]
I've added a Docker section to the README now: https://github.com/smallhadroncollider/brok#docker
