### ISSUE TITLE
Comma after url

### ISSUE THREAD

**Issue by LeventErkok** [smallhadroncollider/brok#3]
Is this intentional?

```
$ cat a
testing http://www.cnn.com, here
$ brok a
*** Checking URLs ***
Fetching complete

*** Results ***

[a]
- Could not connect: http://www.cnn.com,
```

I can see the argument that ',' shouldn't terminate perhaps; but followed by a space (or end of line/file), it might be a good terminator?

**Comment by smallhadroncollider** [comment]
Hmm. This was my first attempt at writing a parser. I think it's a bit too lenient about where characters can be in a URL. Think I need to look at the URL spec in a bit more detail.

I've added a failing test for this. Will try and get it sorted in the next few days.

**Comment by smallhadroncollider** [comment]
Got the parser working on the above example, but it seems to have broken my caching file parsing...

**Comment by LeventErkok** [comment]
Thanks! I'd appreciate a new hackage release if it's not too much trouble!

**Comment by smallhadroncollider** [comment]
Done

**Comment by smallhadroncollider** [comment]
Please do let me know if you find any other URLs that don't work as expected. Or if you're aware of a big list of URLs that I can test against. I'm mostly just using my teaching notes for tests, but that's a fairly limited set.

**Comment by LeventErkok** [comment]
Just tested it, and looks great for my use case! Much appreciated. (Though I do have a feature request, will open a new issue.)
