### ISSUE TITLE
Feature request: short report

### ISSUE THREAD

**Issue by LeventErkok** [smallhadroncollider/brok#4]
Would be great if there was an option to shorten the report, and just print out what failed.

I understand your recommendation is to use: `brok FILES > /dev/null`. But that one prints absolutely nothing while it's working, i.e., not showing the `Fetching http:...` strings. Since it does take a while for brok to work out all the links, it's actually nice to see those fetching messages; but it's absolutely not necessary to see the final report containing hundreds of URLs at the end.

I imagine it would be something like:

  `brok --onlyReportFailures`

or similar; it would work just as today now, except in the final `*** Results ***` section would only list the files/links that had issues. (Or simply say, "all is good" if there's none.)

**Comment by smallhadroncollider** [comment]
Added in `0.1.6` as `--only-failures`. Could do with some work (like showing the number of successful links), but it should do what you're looking for.

**Comment by LeventErkok** [comment]
Fantastic! Works great. Thanks.
