### ISSUE TITLE
Feature request: option for completely disable caching

### ISSUE THREAD

**Issue by LeventErkok** [smallhadroncollider/brok#5]
Would be nice if there was a `--nocache` option that simply didn't use or save the `.brokdb` file.

**Comment by smallhadroncollider** [comment]
If you did `--cache 0` it would not use the cache. But it would still create a `.brokdb`, so I can see that this would be useful.

**Comment by LeventErkok** [comment]
Cool. I didn't realize you could do `--cache 0`. But a `--nocache` is a lot clearer and easier to understand and  not creating `.brokdb` is a plus.

**Comment by smallhadroncollider** [comment]
I've not actually tried it, but it should just ignore all the entries in `.brokdb` if `cache` is set to `0`.

**Comment by smallhadroncollider** [comment]
Added in 0.1.5. Should be on Hackage now.

**Comment by LeventErkok** [comment]
Thanks! Works great.
